{
  "version": 3,
  "status": "error",
  "message": "  /usr/local/lib/python3.9/site-packages/_pytest/python.py:578: in _importtestmodule\n    mod = import_path(self.fspath, mode=importmode)\n/usr/local/lib/python3.9/site-packages/_pytest/pathlib.py:524: in import_path\n    importlib.import_module(module_name)\n/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n<frozen importlib._bootstrap>:1030: in _gcd_import\n    ???\n<frozen importlib._bootstrap>:1007: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:986: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:680: in _load_unlocked\n    ???\n/usr/local/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:170: in exec_module\n    exec(co, module.__dict__)\ntest/example-syntax-error/example_syntax_error_test.py:4: in <module>\n    from example_syntax_error import hello\nE     File \"./test/example-syntax-error/example_syntax_error.py\", line 3\nE       def hello();\nE                  ^\nE   SyntaxError: invalid syntax",
  "tests": []
}
